# Generated by Django 6.0.7 on 2026-08-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='dropoff_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse de descente'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse de montée'),
        ),
    ]
