# Generated by Django 6.0.7 on 2026-08-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_dropoff_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='dropoff_address',
            field=models.CharField(max_length=255, verbose_name='Adresse de descente'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup_address',
            field=models.CharField(max_length=255, verbose_name='Adresse de montée'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Acceptée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
